config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources "maps"
  resources "demo"
  resources "inputs"
  get '/about' => 'welcome#about', :as => "about_us"
  get '/showmap' => 'welcome#showmap', :as => "showmap"

end

app/models/datum.rb
class Datum < ActiveRecord::Base
  belongs_to :map

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :data, :dependent => :destroy
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :title, presence: true # Make sure the owner's name is present.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
require 'csv'
class DemoController < ApplicationController
    def index
    end

    def new
    @map = Map.new
    @map.title = "台灣犯罪事件發生地圖"
    a = CSV.read('public/wheee.csv')
    i = 0
    j = 0
    flag = 0
    a[0].each do |f|
      ["Addr", "地址"].each do |str|
        if f.include? str
          flag = 1
          break
        end
      end
      if flag == 1
        break
      end
      i += 1
    end
    a.each do |f|
      result = Geocoder.search(f[i])
      if not result.empty?
        location = result[0].instance_variable_get(:@data)['geometry']['location']
        label_now = ""
        a[0].count.times do |cnt|
          if cnt != i
            label_now += f[cnt]
            label_now += ' '
          end
        end
        @map.data.build(:lat => location['lat'], :lng => location['lng'], :label => label_now)
      end
      j += 1
      if j == 80
        break
      end
    end
    @map.save
  end
end

app/controllers/inputs_controller.rb
require 'json'
require 'csv'

class InputsController < ApplicationController
  def create
    begin
      @input = Input.new(input_params)
      @input.save
      file = File.read('/public/tag/' + @input.searchtext)
      tag_hash = JSON.parse(file)
      @map = Map.new
      @map.title = @input.searchtext
      tag_hash['result'].each do |dataset|
        file = File.read('/public/dataset/' + dataset)
        dataset_hash = JSON.parse(file)
        dataset_hash['result']['distribution'].each do |d|
          e = d['HB_URL'].partition('TODC')[2]
          a = CSV.read('/public' + e)
          i = 0
          j = 0
          flag = 0
          a[0].each do |f|
            ["Addr", "地址"].each do |str|
              if f.include? str
                flag = 1
                break
              end
            end
            if flag == 1
              break
            end
            i += 1
          end
          a.each do |f|
            result = Geocoder.search(f[i])
            if not result.empty?
              location = result[0].instance_variable_get(:@data)['geometry']['location']
              label_now = ""
              a[0].count.times do |cnt|
                if cnt != i
                  label_now += f[cnt]
                  label_now += ' '
                end
              end
              @map.data.build(:lat => location['lat'], :lng => location['lng'], :label => label_now)
            end
            j += 1
            if j == 80
              break
            end
          end
        end
      end
      @map.save
    rescue
    end
    redirect_to showmap_path
  end

  private
    def input_params
      params.require(:input).permit(:searchtext)
    end
end

app/controllers/maps_controller.rb
require 'csv'

class MapsController < ApplicationController
  def new
    @map = Map.new
  end
  def create
    @map = Map.new(map_params)
    a = CSV.read('public/' + @map.attachment.url)
    i = 0
    j = 0
    flag = 0
    a[0].each do |f|
      ["Addr", "地址"].each do |str|
        if f.include? str
          flag = 1
          break
        end
      end
      if flag == 1
        break
      end
      i += 1
    end
    a.each do |f|
      result = Geocoder.search(f[i])
      if not result.empty?
        location = result[0].instance_variable_get(:@data)['geometry']['location']
        label_now = ""
        a[0].count.times do |cnt|
          if cnt != i
            label_now += f[cnt]
            label_now += ' '
          end
        end
        @map.data.build(:lat => location['lat'], :lng => location['lng'], :label => label_now)
      end
      j += 1
      if j == 80
        break
      end
    end
    @map.save
    redirect_to :showmap
  end

  private
    def map_params
      params.require(:map).permit(:title, :attachment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    @input = Input.new
	end

	def about
	end

	def showmap
		@maps = Map.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <!--<p>Copyright &copy; Yee7Yee3 2015</p>-->
                <p>OpenSource On <a href="https://github.com/deror1869107/Mapper/">Github</a> Yee7Yee3 2015</p>
            </div>
        </div>
    </div>
</footer>

app/views/common/_navbar.html.erb
<div class="brand">Mapper</div>
<div class="subtitle">Visualize your data to fancy maps.</div>

<!-- Navigation -->
<nav class="navbar navbar-default" id="navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="index.html">Mapper</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" id="nav">
                <li>
                    <%= link_to("Home", root_path) %>
                </li>
                <li>
                    <%= link_to("Maps", showmap_path) %>
                </li>
                <li>
                    <%= link_to("Build", new_map_path) %>
                </li>
                <li>
                    <%= link_to("Team", about_us_path) %>
                </li>
                <li>
                    <%= link_to("Demo", demo_index_path) %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/demo/new.html.erb
<div class="container">
  <div class="box">
    <h1>Generate Finish!!</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">
</head>
<body>
<%= render "common/navbar" %>
<%= yield %>
<%= render "common/footer" %>
</body>
</html>

app/views/maps/new.html.erb
<div class="container">
	<div class="box">
		<div class="row">
			<div class="col-md-4">
				<%= simple_form_for @map, html: { multipart: true} do |f| %>
				    <div class="input-group">
						<span class="input-group-addon">標題</span>
						<%= f.text_field :title, :class => 'form-control', :placeholder => 'Title' %>
					</div><br>
					<%= f.file_field :attachment, :id => "file",:class => 'filestyle', :'data-placeholder' => 'No file', :'data-buttonName' => 'btn btn-primary', :'data-buttonText' => '瀏覽檔案' %>
					<br>
					<div class="btn-group btn-group-justified">
						<div class="btn-group">
							<button class="btn btn-info btn-lg" disabled>預覽地圖</button>
						</div>
						<div class="btn-group">
						    <input type="submit" class="btn btn-success btn-lg" value="上傳資料">
						</div>
					</div>
				<% end %>
			</div>
			<div class="col-md-8" style="text-align: center">

				<h1>資料上傳</h1>
				<p>將您的資料視覺化為資訊地圖。<br>
				只要上傳您的資料，我們將為您處理接下來的一切。</p><br>
				<div class="circle" style="margin: auto"><span class="glyphicon glyphicon-list-alt"></span></div>

			</div>
    	</div>
	</div>
</div>

<script>

$(document).ready(function () {

  $("#file").filestyle({buttonText: "瀏覽檔案", buttonName: "btn-primary", placeholder: "No file"});

});
</script>

app/views/welcome/about.html.erb
<div class="container">

    <div class="row">
        <div class="box">
            <div class="col-lg-12 text-center container">
            	<div class="row">
					<h1>About Us</h1>
					<h3>交大男女七比yee，yee對情侶三對基</h3><br>
				</div>
				<div class="row">
		            <div class="col-lg-4 col-sm-6 text-center">
		                <img class="img-circle img-responsive img-center" src="<%= asset_path("deror.jpg") %>" alt="">
		                <h3>宋元堯 Deror <small>CTO</small></h3>
		                <p>負責後端技術，擅長解決各種不可能的任務。</p>
		            </div>
		            <div class="col-lg-4 col-sm-6 text-center">
		                <img class="img-circle img-responsive img-center" src="<%= asset_path("bryce.jpg") %>" alt="">
		                <h3>曹鼎 Bryce <small>CYeeO</small></h3>
		                <p>曹鼎科技創辦人。</p>
		            </div>
		            <div class="col-lg-4 col-sm-6 text-center">
		                <img class="img-circle img-responsive img-center" src="<%= asset_path("peter.jpg") %>" alt="">
		                <h3>鄭景文 Peter <small>Mine Pro</small></h3>
		                <p>技術支援，人稱專業雷隊友。</p>
		            </div>
		        </div>
		        <div class="row">
		            <div class="col-lg-4 col-sm-6 text-center">
		                <img class="img-circle img-responsive img-center" src="<%= asset_path("ag.jpg") %>" alt="">
		                <h3>曾香耘 Ag <small>CMO</small></h3>
		                <p>負責行銷業務，以將好用的服務推廣到全宇宙為己任。</p>
		            </div>
		            <div class="col-lg-4 col-sm-6 text-center">
		                <img class="img-circle img-responsive img-center" src="<%= asset_path("yishen.jpg") %>" alt="">
		                <h3>張楹翔 Yishen <small>UX</small></h3>
		                <p>負責視覺設計，致力於提供使用者一個更簡單易用的介面。</p>
		            </div>
		        </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container -->

app/views/welcome/index.html.erb
<div class="container">
	<div class="row">
        <div class="box" style="text-align: center">
			<h1>Mapper 資訊地圖化</h1>
			<div class="col-lg-12">

                <div id="custom-search-input">
		            <div class="input-group col-md-12">
	            		<%= simple_form_for @input do |f| %>
			                <div class="input-group">
							    <%= f.text_field :searchtext, class: 'form-control input-lg', :placeholder => "搜尋開放資料..." %>
							    <span class="input-group-btn">
							        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
							    </span>
						    </div><!-- /input-group -->
		                <% end %>

						
		            </div>
	            </div>
	            <br>
				<p>連結台灣開放資料庫，為您將您需要的資料，清晰地呈現在地圖上。</p>

			</div>
		</div>
    </div>


</div>
<!-- /.container -->

app/views/welcome/showmap.html.erb
<div class="container">
    <div class="box row">
    	<div class="col-md-4">
            <div id="custom-search-input">
	            <div class="input-group col-md-12">
	                <input type="text" class="form-control input-lg" placeholder="搜尋地圖..." />
	                <span class="input-group-btn">
	                    <button class="btn btn-info btn-lg" type="button">
	                        <i class="glyphicon glyphicon-search"></i>
	                    </button>
	                </span>
	            </div>
            </div>
            <div style="overflow-y: scroll; height: 40em">
				<ul class="nav nav-pills nav-stacked list-group">
				    <% @maps.each do |m| %>
				        <li><a class="list-group-item" data-toggle="tab" href="#<%= m.title %>"><%= m.title %></a></li>
				        
				    <% end %>
			    </ul>
			</div>
		</div>

        <div class="col-md-8 text-center container">

			<% @maps.each do |m| %>
		        <div id="<%= m.title %>" style="position: absolute; width: 95%" class="tab-pane fade">
			        <h1><%= m.title %></h1>
			        <div class="map" style="margin: auto;"></div><br>
			        <div style="text-align: left; font-size: 16px">
			        	<span><i class="glyphicon glyphicon-time"> </i> <%= m.created_at %></span>
			        	<span style="position: absolute; right: 1.5em"><i class="glyphicon glyphicon-map-marker"> </i> <%= m.data.count() %></span>
			        </div>
			    </div>
	        <% end %>

        </div>
    </div>
</div>
<!-- /.container -->


<script>
// Javascript

<% @maps.each do |m| %>
    $('#<%= m.title %> .map').tinyMap({
    'center': '台北市信義區台北101',
    'zoom'  : 14,
     'marker': [
         <% i = 0 %>
        <% m.data.each do |data| %>
            {
            'addr': ['<%= data.lat %>', '<%= data.lng %>'],
            'text': '<strong><%= data.label %></strong>',
            'animation': 'DROP'
        },
        <% end %>
    ]
    });
<% end %>


$(document).ready(function () {
  $('.nav-pills a:first').tab('show')
});
</script>